server:
   port: 8801

logging:
    path: logs
    file: mylog.log


spring:
   application:
          name: report
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3307/school
       username: admin
       password: scott

mybatis:
    type-aliases-package: course.entity
    mapper-locations:
       classpath: mapping/*.xml
