server:
   port: 8888

logging:
    path: logs
    file: mylog.log


spring:
   application:
          name: report
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3307/ssm
       username: admin
       password: scott

mybatis:
    type-aliases-package: com.entity
    mapper-locations:
       - mapper/*
