server:
   port: 8888

logging:
    path: logs
    file: mylog.log

spring:
   application:
          name: report
   datasource:
       driver-class-name: com.mysql.jdbc.Driver
       url: jdbc:mysql://localhost:3307/company
       username: admin
       password: scott
   thymeleaf:
     cache: false
     content-type: text/html
   mail:
      host: smtp.qq.com
      username: 1507718378@qq.com
      password: mouompwksenfbaab
      properties.mail.smtp.auth: true
      properties.mail.smtp.starttls.enable: true
      properties.mail.smtp.starttls.required: true
      port: 587
      default-encoding: utf-8
mybatis:
    type-aliases-package: com.entity
    mapper-locations:
       - mapper/*
